//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> IsInterestedInCSharp { get; set; }
        public Nullable<bool> IsInterestedInJava { get; set; }
        public Nullable<bool> IsInterestedInPython { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual tbl_City tbl_City { get; set; }
    }
}
